name: MOG-ANTICHEAT
version: 1.0.0
main: com.mogdeveloping.mogac.MOGAC
author: MOG-Developing
description: A comprehensive anti-cheat solution for Minecraft servers
commands:
  mogac:
    description: Main command for MOG-ANTICHEAT
    aliases: [moganticheat, ac]
    permission: mogac.admin
permissions:
  mogac.admin:
    description: Allows access to all MOG-ANTICHEAT commands
    default: op
  mogac.alerts:
    description: Allows receiving alerts when players are detected cheating
    default: op
  mogac.bypass:
    description: Allows bypassing all checks
    default: op